In [1]:
import pandas as pd
from alpaca_trade_api.rest import REST, TimeFrame, TimeFrameUnit
from datetime import datetime,timedelta, timezone

In [2]:
# initialize alpaca
api = REST(key_id = 'PKU9G2XRSNL8A1FF34C7', secret_key = 'AQe6RsvUdmZykRZCRYsNF5kEogta6DIyCApkoMAl'
          ,base_url = "https://paper-api.alpaca.markets")

In [3]:
from datetime import date as todaysDate
from datetime import datetime as todaysDateTime
Today_date  =  todaysDate.today()
Today_time  =  todaysDateTime.min.time()
Today_datetime = todaysDateTime.combine(Today_date, Today_time)
print(Today_datetime)

2022-07-14 00:00:00

In [4]:
api.get_calendar("2022-07-04")

[Calendar({   'close': '16:00',
     'date': '2022-07-05',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-06',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-07',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-08',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-11',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-12',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-13',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-14',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-15',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-18',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-19',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-20',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-21',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-22',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-25',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-26',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-27',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-28',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-07-29',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-01',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-02',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-03',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-04',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-05',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-08',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-09',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-10',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-11',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-12',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-15',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-16',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-17',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-18',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-19',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-22',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-23',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-24',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-25',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-26',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-29',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-30',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-08-31',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-01',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-02',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-06',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-07',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-08',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-09',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-12',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-13',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-14',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-15',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-16',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-19',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-20',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-21',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-22',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-23',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-26',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-27',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-28',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-29',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-09-30',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-03',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-04',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-05',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-06',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-07',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-10',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-11',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-12',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-13',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-14',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-17',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-18',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-19',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-20',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-21',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-24',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-25',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-26',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-27',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-28',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-10-31',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-01',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-02',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-03',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-04',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-07',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-08',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-09',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-10',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-11',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-14',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-15',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-16',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-17',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-18',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-21',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-22',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-23',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '13:00',
     'date': '2022-11-25',
     'open': '09:30',
     'session_close': '1600',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-28',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-29',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-11-30',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-01',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-02',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-05',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-06',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-07',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-08',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-09',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-12',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-13',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-14',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-15',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-16',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-19',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-20',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-21',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-22',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-23',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-27',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-28',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-29',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2022-12-30',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-03',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-04',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-05',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-06',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-09',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-10',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-11',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-12',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-13',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-17',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-18',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-19',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-20',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-23',
     'open': '09:30',
     'session_close': '2000',
     'session_open': '0400'}),
 Calendar({   'close': '16:00',
     'date': '2023-01-24',
     'open': '09:30',
     'session_close': '2000',

In [5]:
datetime(1970,1,1)

datetime.datetime(1970, 1, 1, 0, 0)

In [20]:
api.get_crypto_bars("GRUB",
                                #TimeFrame(1, TimeFrameUnit.Minute),
                                TimeFrame.Hour,
                                start = "2021-01-01",
                                end=None
                               
                                ).df.reset_index()

Empty DataFrame
Columns: [index]
Index: []

In [58]:
tickers= [
    'RDS.A',
    'GWPH',
    'ERUS',
    'CREE',
    'CZZ',
    'RDS.B',
    'RUSL',
    'GRUB',
    'QIWI',
    'VIAC',
    'DISCK',
    'KSU',
    'BLANK',
    'TIF',
    'DNKN',
    'UN',
    'GRA',
    'LB'
]

In [32]:
df = api.get_bars('GRUB',
                                #TimeFrame(1, TimeFrameUnit.Minute),
                                TimeFrame.Hour,
                                start = "2022-01-01",
                                end = None
                                ).df.reset_index()

In [33]:
df

,timestamp,open,high,low,close,volume,trade_count,vwap
0,2022-01-03 09:00:00+00:00,10.9400,11.2000,10.90,11.18,64921,163,10.964407
1,2022-01-03 10:00:00+00:00,11.1800,11.2600,11.13,11.18,26306,92,11.186941
2,2022-01-03 11:00:00+00:00,11.1800,11.1800,11.10,11.11,20753,34,11.112834
3,2022-01-03 12:00:00+00:00,11.1100,11.1600,11.10,11.16,29771,69,11.123157
4,2022-01-03 13:00:00+00:00,11.1300,11.2600,11.11,11.25,59830,126,11.181260
...,...,...,...,...,...,...,...,...
646,2022-03-11 20:00:00+00:00,6.9262,6.9599,6.72,6.73,1167702,5665,6.796419
647,2022-03-11 21:00:00+00:00,6.7200,6.9000,6.70,6.90,68006,19,6.720475
648,2022-03-11 22:00:00+00:00,6.7900,6.7900,6.73,6.73,851,6,6.772303
649,2022-03-11 23:00:00+00:00,6.7300,6.7300,6.73,6.73,800,1,6.730000
650,2022-03-12 00:00:00+00:00,6.7300,6.7300,6.73,6.73,600,2,6.730000

In [7]:
df.groupby('symbol')['timestamp'].max()

KeyError: 'symbol'

In [18]:
df = api.get_bars("ARKK",
                                #TimeFrame(1, TimeFrameUnit.Minute),
                                TimeFrame.Hour,
                                start = "2022-07-01",
                                end = None
                                ).df.reset_index()

In [19]:
df

,timestamp,open,high,low,close,volume,trade_count,vwap
0,2022-07-01 08:00:00+00:00,39.70,39.720,39.400,39.500,3696,45,39.483093
1,2022-07-01 09:00:00+00:00,39.70,39.780,39.700,39.780,5879,39,39.717666
2,2022-07-01 10:00:00+00:00,39.80,39.900,39.750,39.750,1538,18,39.860325
3,2022-07-01 11:00:00+00:00,39.70,39.980,39.600,39.640,41589,342,39.775519
4,2022-07-01 12:00:00+00:00,39.80,40.030,39.710,39.960,65784,642,39.865690
5,2022-07-01 13:00:00+00:00,39.96,41.810,39.960,41.310,5188962,37463,40.859706
6,2022-07-01 14:00:00+00:00,41.30,41.670,40.260,40.980,5437301,34861,40.965696
7,2022-07-01 15:00:00+00:00,40.97,41.460,40.570,40.710,2586354,18423,41.084595
8,2022-07-01 16:00:00+00:00,40.69,40.820,40.315,40.330,1706834,11918,40.582865
9,2022-07-01 17:00:00+00:00,40.32,40.790,40.200,40.770,1755183,11062,40.530743
10,2022-07-01 18:00:00+00:00,40.77,41.050,40.430,40.905,1540313,10297,40.794678
11,2022-07-01 19:00:00+00:00,40.91,41.225,40.740,41.190,4220931,25376,41.057644
12,2022-07-01 20:00:00+00:00,41.22,41.380,41.100,41.210,1334662,242,41.217708
13,2022-07-01 21:00:00+00:00,41.19,41.390,40.480,41.250,40840,113,41.082688
14,2022-07-01 22:00:00+00:00,41.28,41.280,41.130,41.130,2079,11,41.215248
15,2022-07-01 23:00:00+00:00,41.13,41.370,41.110,41.340,16756,94,41.262118
16,2022-07-05 08:00:00+00:00,41.40,41.400,40.520,40.520,11438,77,40.966859
17,2022-07-05 09:00:00+00:00,40.55,40.810,40.500,40.690,16221,103,40.580192
18,2022-07-05 10:00:00+00:00,40.66,40.850,40.640,40.850,8146,37,40.721241
19,2022-07-05 11:00:00+00:00,40.83,40.840,40.440,40.440,28052,223,40.695526
20,2022-07-05 12:00:00+00:00,40.45,40.720,40.200,40.240,136288,1345,40.492600
21,2022-07-05 13:00:00+00:00,40.24,41.230,39.840,40.930,4999277,35338,40.441958